EntityFramework/EntityFramework/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Content> Contents { get; set; }
    }
}

EntityFramework/EntityFramework/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Models
{
    public class Comment
    {
        public int Id { get; set; }
        public User User { get; set; }
        public int ContentId { get; set; }
        public string Description { get; set; }
        public int Rate { get; set; }
    }
}

EntityFramework/EntityFramework/Models/Content.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Models
{
    public class Content
    {
        public int Id { get; set; }
        public ICollection<Category> Categories { get; set; }
        public string Title { get; set; }
        public DateTime UpdateDate { get; set; }
        public string Article { get; set; }
        public ICollection<Comment> Comments { get; set; }
    }
}

EntityFramework/EntityFramework/Models/ContentContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Models
{
    public class ContentContext:DbContext
    {
        public ContentContext(DbContextOptions options) : base(options)
        {

        }

        public DbSet<Category> Categories { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Content> Contents { get; set; }
    }
}

EntityFramework/EntityFramework/Models/ContentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Models
{
    public class ContentViewModel
    {
        public int Id { get; set; }
        public List<Category> Categories { get; set; }
        public string Title { get; set; }
        public DateTime UpdateDate { get; set; }
        public string Article { get; set; }
        public List<Comment> Comments { get; set; }
    }
}

EntityFramework/EntityFramework/Models/ErrorViewModel.cs
using System;

namespace EntityFramework.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EntityFramework/EntityFramework/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Models
{
    public class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public ICollection<Comment> Comments { get; set; }
    }
}

EntityFramework/EntityFramework/Controllers/CategoryController.cs
using EntityFramework.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ContentContext _context = null;
        public CategoryController(ContentContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CategoryAdd()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CategoryAdd(Category category)
        {
            await _context.Categories.AddAsync(category);
            await _context.SaveChangesAsync();
            return RedirectToAction("Add", "Content");
        }

    }
}

EntityFramework/EntityFramework/Controllers/ContentController.cs
using EntityFramework.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Controllers
{
    public class ContentController : Controller
    {      
        private readonly ContentContext _context = null;
        public ContentController(ContentContext context)
        {
            _context = context;
        }
        
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Add()
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Add(Content model)
        {
            await _context.Contents.AddAsync(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        public async Task<IActionResult> Contents()
        {
            ViewBag.Contents = await _context.Contents.ToListAsync();
            //ViewBag.Contents.Clear();
            return View();
        }
        public async Task<IActionResult> ContentDetail(int id)
        {
            var contents = await _context.Contents.ToListAsync();
            var contentt= contents.Where(e => e.Id == id).ToList().FirstOrDefault();
            ViewBag.ContentDetail = contentt;
            try
            {
                ViewBag.Comments = await _context.Comments.ToListAsync();
            }
            catch (Exception)
            {

            }
            
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> AddComment(Comment comment)
        {                    
            await _context.Comments.AddAsync(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Contents");
        }
    }
}

EntityFramework/EntityFramework/Controllers/HomeController.cs
using EntityFramework.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EntityFramework/EntityFramework/Controllers/UserController.cs
using EntityFramework.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFramework.Controllers
{
    public class UserController : Controller
    {
        private readonly ContentContext _context;
        public UserController(ContentContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddUser()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddUser(User user)
        {
            await _context.Users.AddAsync(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }
    }
}

EntityFramework/EntityFramework/Views/Category/CategoryAdd.cshtml
@model Category
    <h1>Kategori Ekleme Sayfası</h1>
<form asp-action="CategoryAdd" method="post">
    <div class="form-group">
        <label class="control-label">Kategori Adı</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div>
        <input type="submit" class="btn btn-primary" value="Ekle"/>
    </div>
</form>

EntityFramework/EntityFramework/Views/Content/Add.cshtml
@model Content
<form asp-action="Add" method="post">
    <div class="form-group">
        <label class="control-label">Başlık</label>
        <input asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label class="control-label">Makale</label>
        <input asp-for="Article" class="form-control" />
    </div>
    <div class="form-group">
        <label class="control-label">Tarih</label>
        <input asp-for="UpdateDate" class="form-control" />
    </div>
    <div class="form-group">
        <select asp-for="Categories" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))" multiple>
            <option>Lütfen Kategori seçiniz...</option>
        </select>
    </div>

    <div>
        <input type="submit"  class="btn btn-primary" value="Ekle"/>
    </div>
</form>

EntityFramework/EntityFramework/Views/Content/ContentDetail.cshtml
@model Comment
<div class="row">
    <div class="card col-md-12 text-center" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@ViewBag.ContentDetail.Title</h5>
            <h6 class="card-subtitle mb-2 text-muted">@ViewBag.ContentDetail.UpdateDate</h6>
            <p class="card-text">@ViewBag.ContentDetail.Article</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-6">
        <h2 class="text-center">Yorumlar</h2>
        @if (ViewBag.Comments != null)
        {

       
        foreach (var comment in ViewBag.Comments)
        {
            if (comment.ContentId == ViewBag.ContentDetail.Id)
            {
                <h5>@comment.Rate</h5>
                <h6>@comment.Description</h6>
            }

        }
        }
    </div>
    <div class="col-6">
        <form asp-action="AddComment">
            <h3 class="text-center">Yorum Ekle</h3>
            <input asp-for="ContentId" class="form-control" readonly  value="@ViewBag.ContentDetail.Id" type="hidden"/>
            <div class="form-group">
                <label asp-for="Rate">Rate</label>
                <select class="form-control" asp-for="Rate">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Description">Yorum</label>
                <textarea class="form-control" asp-for="Description" rows="3"></textarea>
            </div>

            <input type="submit" class="btn btn-primary" value="Ekle" />
        </form>
    </div>
</div>

EntityFramework/EntityFramework/Views/Content/Contents.cshtml
@model List<Content>
<div class="row">
    @foreach (var content in ViewBag.Contents)
    {
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@content.Title</h5>
                <p class="card-text">@content.Article</p>
                <a href="/Content/ContentDetail?id=@content.Id" class="btn btn-primary">Detay</a>
            </div>
        </div>    
    }
</div>

EntityFramework/EntityFramework/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EntityFramework/EntityFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EntityFramework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EntityFramework</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Content" asp-action="Contents">Makaleler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Content" asp-action="Add">Makale Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="CategoryAdd">Kategori Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AddUser">User Ekle</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EntityFramework - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>